### ISSUE TITLE
Implement std::error::Error for keypass::OpenDBError

### ISSUE THREAD

**Issue by Dr-Emann** [sseemayer/keepass-rs#1]
It would be nice if `OpenDBError` implemented [std::error::Error](http://doc.rust-lang.org/stable/std/error/trait.Error.html).

In order for `OpenDBError` to implement `Error`, the following needs to be decided:

* `Error` requires its implementers to implement `Debug` and `Display`. `OpenDBError` already implements `Debug`, but it would also have to be able to display itself in a pretty way. I don't know enough about the domain to know if there is a simple "nice" string representation for the types of errors.
* `Error` requires a `.description(&self) -> &'static str` function. It's probably enough to have a simple static string for each variant, and return that. (see what `std::error::Error` [does](http://doc.rust-lang.org/stable/src/std/io/error.rs.html#312))

**Comment by sseemayer** [comment]
In implementing this, I learned that the [crypto::symmetriccipher::SymmetricCipherError](http://ironframework.io/doc/crypto/symmetriccipher/enum.SymmetricCipherError.html) doesn't implement Error yet. I still have to make the `DecompressionError` also implement Error but was wondering if I'm understanding the purpose of the `fmt` function of the `Display` trait (to format a user-facing error message?) versus the purpose of the `description` function of the `Error` trait (to give a shorter description?). Am I on the right track here?

**Comment by Dr-Emann** [comment]
That's pretty much the case: `Display::fmt` should be user facing, but still give a good amount of information (io::error prints both the pretty string (e.g. "Read-only file system"), and the os error code number (e.g. "os error 30")) `Error::description` should give as much information as it can, given the str it returns must be `'static`.

**Comment by sseemayer** [comment]
Done. I think now the error handling is perfect. What do you think?

**Comment by Dr-Emann** [comment]
I made some comments on the commit, but this issue looks done to me. Looks good.
