### ISSUE TITLE
Access custom AutoType keystroke sequences

### ISSUE THREAD

**Issue by sts10** [sseemayer/keepass-rs#10]
Do you know if there's any way to access the custom AutoType sequence of an entry? 

I'm referring to the string of text "{USERNAME}{DELAY 1000}{TAB}{PASSWORD}{ENTER}" in the screenshot below:

![screenshot_20190205_202903](https://user-images.githubusercontent.com/4871664/52315389-b922d380-2984-11e9-96f0-f1f0a72ba7e7.png)

I've been trying things like `e.get("AutoType")`, `e.get("AutoTypeSequence")` and `e.get("KeystrokeSequence")` but no dice apparently.

I also [searched the KeePassXC repo for "sequence"](https://github.com/keepassxreboot/keepassxc/search?q=sequence&unscoped_q=sequence) for more ideas both only got errors. 

Any ideas?

**Comment by sseemayer** [comment]
Whoops, my bad. AutoType settings are stored in a different place in the underlying XML file. I've [added some structs and the corresponding parsers](https://github.com/sseemayer/keepass-rs/commit/488924402814185d1eb47e920d8be36b77c3191b) and they should be available in version 0.3.2.
