### ISSUE TITLE
in https://keepass-diff.narigo.dev/ , missing download and contact links

### ISSUE THREAD

**Issue by micgrivas** [sseemayer/keepass-rs#107]
I want to use this tool, without installing RUST. 
There is a command to create the docker image, which raises these two questions:
- Why don't you provide the image?
- The build command expects Containerfile.install. But there is no link to it. Using RUST we can get it, but then we won't need it.

In the last line of that page it says "please reach out!"  but there is no link for how to reach out.

**Comment by sseemayer** [comment]
Hi @micgrivas , you have reached the wrong project - this is the keepass library that [keepass-diff](https://github.com/Narigo/keepass-diff) is based on. You probably want to ask your question there.
