### ISSUE TITLE
Support deleted objects tag

### ISSUE THREAD

**Issue by louib** [sseemayer/keepass-rs#114]
This was mentioned [here](https://github.com/sseemayer/keepass-rs/pull/106#issuecomment-1416203164).
See also the comment [here](https://github.com/sseemayer/keepass-rs/blob/113fcb6c485dc321bc26ebbcc057f681bca3fc61/src/xml_db/dump/meta.rs#L118).
I think this is the only field that we observed in the KeePassXC database dump that is not implemented yet.

**Comment by sseemayer** [comment]
I am not 100% certain that nothing else is missing, but agree that deleted objects should be added, probably as another member of `Database`.
