### ISSUE TITLE
Feature to encrypt a Keepass database

### ISSUE THREAD

**Issue by wusyong** [sseemayer/keepass-rs#14]
Really nice to have this useful lib in rust. However, it seems there's no way to save to a keepass file at the moment. Does it plan to add so?

**Comment by sseemayer** [comment]
This would be a big amount of additional work. I am currently not planning to implement this myself but would be willing to accept PRs if anyone is willing to make progress on this.

**Comment by louib** [comment]
Re-opening this issue until we have the feature available as a feature flag.

**Comment by sseemayer** [comment]
#106 will make an experimental version of this available.

**Comment by sseemayer** [comment]
Version 0.6.0-rc.1 is now out for testing on crates.io - experiences with the feature from a broader audience would be appreciated!

**Comment by louib** [comment]
@sseemayer do you feel comfortable publishing version `0.6`? I don't think the `rc` versions have as much visibility, and the kdbx saving feature would still be behind a feature flag. I think it would generate more feedback if we publish a non-rc version.

**Comment by sseemayer** [comment]
version `0.6.0` is now out on crates.io

**Comment by sseemayer** [comment]
We have this available as a feature flag, so closing.
