### ISSUE TITLE
keepass-rs panics if providing a defect kdbx file

### ISSUE THREAD

**Issue by ahrensburger** [sseemayer/keepass-rs#191]
When you provide a defect kdbx file (in detail: a kdbx file with a size less than 12 byte) to Database::open(), it will panic in DatabaseVersion::parse() due to slice operations without a previous length check.

Happened accidently to me, since I provided the same File object twice to Database::open(), being at EOF position the second time (due to the source.read_to_end() call in Database::open()).

**Comment by louib** [comment]
@ahrensburger thanks for the bug report! That should be pretty easy to fix.
