### ISSUE TITLE
Database::open() should use generic parameter

### ISSUE THREAD

**Issue by ahrensburger** [sseemayer/keepass-rs#193]
Thanks again for fixing the bug I ran into. :-)

I'd further more like to use a database stored on an S3 bucket, using crate s3reader right away, which implements the read trait. Therefore it would be really helpful, if Database::open() would support specifying a class implementing the std::io::Read trait, as such (or similar):

pub fn open<R: std::io::Read>(
        source: &mut dyn R,
        key: DatabaseKey,
    ) -> Result<Database, DatabaseOpenError> {
    ...
    }

I didn't compile and test it, but I hope you got my point. :-)

**Comment by louib** [comment]
@ahrensburger in the meantime, you can also use the `parse(data: &[u8], key: DatabaseKey)` function, which I introduced when fixing the first bug you reported.

**Comment by sseemayer** [comment]
@ahrensburger are you sure this isn't already possible? The [`Database::open` signature](https://github.com/sseemayer/keepass-rs/blob/b95c80cae79644417731bac21d595c9f37edfd8b/src/db/mod.rs#L60-L63) takes `source: &mut dyn std::io::Read`, which should be compatible with the `S3Reader`.

**Comment by sseemayer** [comment]
Closing as current solution is probably good enough, please feel free to re-open with more context.
