### ISSUE TITLE
Fix code coverage job

### ISSUE THREAD

**Issue by louib** [sseemayer/keepass-rs#222]
The code coverage job has been failing recently with [this error](https://github.com/sseemayer/keepass-rs/actions/runs/8777268097/job/24104045982#step:5:87). I think we now need a codecov token in order to upload the results, as seen in [the usage documentation for the action](https://github.com/codecov/codecov-action?tab=readme-ov-file#usage). I think we should also bump `codecov/codecov-action` to `v4` at the same time.

@sseemayer I don't have the permissions to create a token in codecov, and I don't have admin access to this repo, so I can't handle the token provisioning myself.

**Comment by sseemayer** [comment]
Unfortunately I don't see an option to make you an admin to the repo, but I've added a token secret and bumped the CI tool versions in the attached PR.
