### ISSUE TITLE
Opening of KDBX 3.1 file seems to be very slow

### ISSUE THREAD

**Issue by Narigo** [sseemayer/keepass-rs#25]
@pludi reported this in [keepass-diff](https://github.com/Narigo/keepass-diff/issues/24). 

I have done some additional debugging with the provided files. The `transformation_rounds` when parsing the header is set to`32804232` and thus the [encryption for-loop](https://github.com/sseemayer/keepass-rs/blob/eb1cec859cc7257830882c2434560d19226cdc31/src/crypt/kdf.rs#L28-L39) runs very often. Since my Keepass client (not keepass-diff) can open these files pretty quickly, I wonder how that really works...

**Additional context**
- [Test1.kdbx.gz](https://github.com/Narigo/keepass-diff/files/4879056/Test1.kdbx.gz), Password: `Test1`
- [Test2.kdbx.gz](https://github.com/Narigo/keepass-diff/files/4879057/Test2.kdbx.gz), Password: `Test2`
- Initial issue report by @pludi over here: https://github.com/Narigo/keepass-diff/issues/24

**Comment by sseemayer** [comment]
Please have a look at https://github.com/sseemayer/keepass-rs/blob/master/README.md#installation , especially the note about performance :)

**Comment by Narigo** [comment]
As stated in the other PR, even with the flags enabled, it still took a while to open. Is there another flag I should be using other than what I have written down in [the comment](https://github.com/Narigo/keepass-diff/issues/24#issuecomment-654520482)?

Regarding the flags itself: Do you know whether it is possible to put the necessary flag into Cargo when compiling as dependency? I'd like to not have the user have to analyse dependencies and set the flags that would be necessary for each of them. There is a setting for `rustflags` in [Cargo configuration](https://doc.rust-lang.org/cargo/reference/config.html) but I've never used or tried that...

**Comment by sseemayer** [comment]
Sorry for the short reply before. This seems to be a real issue with the performance of the AES key derivation.

I can also see that even with the compiler flags and doing a release build, this library is still considerably slower than what e.g. keepassxc needs to derive the key.

On my mobile Core i5-8250U, with the CFLAGS set, a release run of the `tests::open_kdbx4_with_password_kdf_aes_cipher_aes` takes 17 seconds to open while opening [the same database](tests/resources/test_db_kdbx4_with_password_aes.kdbx) is instantaneous.

**Comment by sseemayer** [comment]
Hang on, no! If I export the correct RUSTFLAGS and do a release build, the test completes in less than half a second for me. It seems that my first attempt at adding the config via a file was incorrect.

**Comment by sseemayer** [comment]
I've added the rustflags to the cargo config now as well. Let me know if that together with a Release build helps bring the loading time down.

**Comment by Narigo** [comment]
I have updated to version `0.4.7` now and tried to set the `RUSTFLAGS` in `.cargo/config.toml` as well as having it as environment variables during the run. The following output of the Docker environment yield very long opening times still with kdbx 3.1 files:

```
root@cb29c1f5ec07:/app# time RUSTFLAGS="-C target-cpu=native" cargo run --release test/test.kdbx test/test2.kdbx --password-a demopass --password-b demopass --no-color
    Finished release [optimized] target(s) in 0.18s
     Running `target/release/keepass-diff test/test.kdbx test/test2.kdbx --password-a demopass --password-b demopass --no-color`
+ [Root, Another group, In another group]
- [Root, Some group, Sub-Group 2 of group, Walked, Password = line]
+ [Root, Some group, Sub-Group 2 of group, Walked, Password = plank]
+ [Root, Some group, Sub-Group 2 of group, Whatever, that = means]
- [Root, Some group, In a group]
+ [Root, One more]


real    0m0.421s
user    0m0.238s
sys     0m0.051s
root@cb29c1f5ec07:/app# time RUSTFLAGS="-C target-cpu=native" cargo run --release test/issue-24-kdbx-3.1/Test1.kdbx test/issue-24-kdbx-3.1/Test2.kdbx --password-a Test1 --password-b Test2 --no-color
    Finished release [optimized] target(s) in 0.17s
     Running `target/release/keepass-diff test/issue-24-kdbx-3.1/Test1.kdbx test/issue-24-kdbx-3.1/Test2.kdbx --password-a Test1 --password-b Test2 --no-color`
- [Root, Test1]
+ [Root, Test2]


real    0m57.413s
user    0m57.281s
sys     0m0.049s
```

Maybe I'm still doing something wrong here...?

The code I'm testing with is in branch `update-dependencies` in the `keepass-diff` repository: https://github.com/Narigo/keepass-diff/tree/8b8e46d61dc0efc80bef7fc310262d18c0140f63

By the way, since I've updated to 0.4.7, [the Value::Bytes pattern](https://docs.rs/keepass/0.4.7/keepass/enum.Value.html#variant.Bytes) had to be implemented. Does [my implementation](https://github.com/Narigo/keepass-diff/blob/8b8e46d61dc0efc80bef7fc310262d18c0140f63/src/diff/entry.rs#L25) even make sense? Or could a bytes array be anything in Keepass, so I maybe should try to convert it to a hash value and test against that?

**Comment by Narigo** [comment]
Hmm, using `cargo install --path .` seems to do some other optimizations? At least it's down to 7s now, but that's still quite long compared to the 1s for other kdbx files, isn't it?

**Comment by sseemayer** [comment]
Sorry, I cannot reproduce this - Testing on 8b8e46, 

Your first invocation

```
$ time RUSTFLAGS="-C target-cpu=native" cargo run --release test/test.kdbx test/test2.kdbx --password-a demopass --password-b demopass --no-color
```

takes me 0.07s and 

your second invocation 
```
$ time RUSTFLAGS="-C target-cpu=native" cargo run --release test/issue-24-kdbx-3.1/Test1.kdbx test/issue-24-kdbx-3.1/Test2.kdbx --password-a Test1 --password-b Test2 --no-color
```

takes 6.35s. 

![timing](https://user-images.githubusercontent.com/736556/99197203-3ce03580-2791-11eb-98a0-cfeb89dcd25d.png)


If I open the same two database files as in your second invocation using keepassxc, this takes about 2 seconds for each of the databases (I didn't really time this but this is a rough estimate), so it looks like this is close to an "optimal" key derivation speed.

**Comment by sseemayer** [comment]
Since the key derivation function for the slow databases is AES, can you confirm that your system's CPU is supporting AES hardware instructions (the `aes` flag)?

```
$ grep flags /proc/cpuinfo | head -n1
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
```

**Comment by Narigo** [comment]
I'm doing this on a Mac with Docker. In Docker, it shows me the following (= I guess so?):

```
root@cadaa7cf56f6:/app# grep flags /proc/cpuinfo | head -n1
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch pti fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
```

**Comment by sseemayer** [comment]
Yeah, it looks like it's supported. Hmm.

Another thing we could check is whether the release binary gets compiled with hardware AES instructions by disassembling it, e.g.:

```
$ objdump -d target/release/keepass-diff | grep vaes | cut -f3 | cut -f1 -d ' ' | sort | uniq -c | sort -rn
    143 vaesenc
    117 vaesdec
     13 vaeskeygenassist
     13 vaesimc
     11 vaesenclast
      9 vaesdeclast
```

**Comment by Narigo** [comment]
I think this should be okay now: Without the usage of docker, I get a lot better performance, so it's probably not really the fault of the keepass module. It still takes a few seconds to open these files but the flags really work well enough I suppose. See https://github.com/Narigo/keepass-diff/issues/24#issuecomment-733047796 as well. Thanks for your help in debugging this and sorry for the additional noise...! 🙂
