### ISSUE TITLE
Preserve order (BTreeMap?)

### ISSUE THREAD

**Issue by leaty** [sseemayer/keepass-rs#28]
The order is lost on groups when iterating.

**Disclaimer**: I've not looked at the internals of this crate nor the keepass format.

Assuming this crate reads everything in order from the .kdbx file, a `BTreeMap` would retain said order. If not, perhaps there is an order index somewhere on each group which could help?

**Comment by sseemayer** [comment]
The keepass format is an encrypted XML document, so the order should be contained there. Currently, the entries are [stored in a HashMap](https://github.com/sseemayer/keepass-rs/blob/master/src/db.rs#L276-L285) so the fix for this should be fairly easy. Would you be interested in providing a PR?

**Comment by leaty** [comment]
Thanks for confirming my suspicion.

Absolutely, will do.
