### ISSUE TITLE
Add "Expires" struct to both Group and Entry

### ISSUE THREAD

**Issue by jgrussell** [sseemayer/keepass-rs#29]
I am planning to use this crate for a small personal project not only to familiarize myself with Rust but also to use as a [hopefully] short term solution to this KeePassXC feature request that has been around in one form or another for several years.
https://github.com/keepassxreboot/keepassxc/issues/4624

In my limited testing so far, I have found this crate very easy to use and robust.  However, it does not provide access to the Group or Entry expiration information which I will need for my project.  If there is no interest in merging something like that into this crate, I will only do enough work to fulfill my own needs.  However, I think this might be useful to others; so, I am more than willing to fully build this feature out for inclusion here.

My initial plan is to loosely model a new Expires struct and associated population on the existing AutoType struct.  

Additionally, I will probably also want to add an Exclude from database reports indicator on Entry.  For this, I am thinking a new bool in Entry would suffice.

I welcome (and will appreciate) any feedback on both the likely inclusion of these features into this crate as well as my planned approach.

Thank you.

**Comment by sseemayer** [comment]
This sounds good to me, and I would be willing to merge something like this.

How is the Expires field encoded in the KDBX? Is it a XML element similar to how AutoType works?

**Comment by jgrussell** [comment]
Expires looks to be encoded similarly to a very basic AutoType, without AutoType's complication of allowing multiple Window Associations, each window optionally allowing for its own auto-type sequence.

If my cursory analysis holds, my new Expires should be much simpler to implement than your AutoType.

I haven't yet looked through all of your existing test .kdbx files; but, if none of them have groups and entries with expiration dates set, do you prefer that I update existing .kdbx files (assuming I can do so without breaking your existing tests) or create new .kdbx files to support my new integration tests of this new functionality?

Finally, thank you so much for both providing this crate and for the quick responses to this issue.

**Comment by sseemayer** [comment]
Sounds good! I don't see an issue with modifying the existing test .kdbx files since they don't check the expiration logic in any way.

Thanks to you for the great idea for another feature :)

**Comment by jgrussell** [comment]
I have created #36 showing where I am going with this and asking for some specific help with converting a Base64 encoded elapsed seconds value to a u64 value.

Thank you.

**Comment by jgrussell** [comment]
#38 adds this functionality.
