### ISSUE TITLE
Implement From<InnerErrors> for OpenDbError

### ISSUE THREAD

**Issue by Dr-Emann** [sseemayer/keepass-rs#3]
If you implement `From<std::io::Error>`, `From<keypass::decompress::DecompressionError>` and `From<crypto::symmetriccipher::SymmetricCipherError>` for [`OpenDbError`](https://github.com/sseemayer/keepass-rs/blob/ea4c33b82b64239ba71b69172fb571a8628fb527/src/lib.rs#L66), you can eliminate the need to call .map_err() on any io errors when using `try!` [here](https://github.com/sseemayer/keepass-rs/blob/c835f3100aa72b3aeef8a6d13558aa2f0e223e7d/src/lib.rs#L134), [here](https://github.com/sseemayer/keepass-rs/blob/c835f3100aa72b3aeef8a6d13558aa2f0e223e7d/src/lib.rs#L249), [here] (https://github.com/sseemayer/keepass-rs/blob/c835f3100aa72b3aeef8a6d13558aa2f0e223e7d/src/lib.rs#L257), and [here](https://github.com/sseemayer/keepass-rs/blob/c835f3100aa72b3aeef8a6d13558aa2f0e223e7d/src/lib.rs#L300)

**Comment by sseemayer** [comment]
That's an awesome tip, thanks! I think the commit above should do it.

**Comment by Dr-Emann** [comment]
Yep, looks good to me, closing!
