### ISSUE TITLE
Bump Edition to 2018

### ISSUE THREAD

**Issue by jgrussell** [sseemayer/keepass-rs#37]
What would you think of bumping the edition for this from its current, default, 2015 to the latest 2018?

This will require a few, hopefully minor, source code changes which I am willing (and I believe able) to tackle after completing #29, assuming you think this is worthwhile.

**Comment by sseemayer** [comment]
I am all for it! I would bet that this will be [auto-fixable by Cargo](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#updating-your-code-to-be-compatible-with-the-new-edition).

**Comment by jgrussell** [comment]
Very cool!  I did try just bumping the edition to allow me to use some specific techniques in #29 ; but, as you might have guessed, that caused more issues than it resolved.  I'll tackle this as time permits if no one else does it first.

**Comment by sseemayer** [comment]
I ended up doing it myself in the same go as implementing the XML dumping tool :)
