### ISSUE TITLE
Update aes version as package got yanked

### ISSUE THREAD

**Issue by Narigo** [sseemayer/keepass-rs#40]
It seems like there were some major updates to the `aes` package and the currently used `0.3.2` version even got a `cargo yank`.

I haven't looked into what changes would be necessary, I only got the heads-up thanks to people failing to install [keepass-diff#34](https://github.com/Narigo/keepass-diff/issues/34) without the `--locked` flag.

**Comment by sseemayer** [comment]
Thanks for reporting and sorry it took a bit of time for me to fix things. I've now released v0.4.9 with all dependencies updated to the newest versions.
