### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by louib** [sseemayer/keepass-rs#77]
I want to add a GHA workflow that automates releases to `crates.io`. I propose using a variant of [semantic-release](https://github.com/semantic-release/semantic-release), which uses [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to determine the next release number and generate the release notes. I would also add a `CI` step that validates the format of the commit message, which would make the git history more consistent and helpful. @sseemayer let me know what you think.

**Comment by sseemayer** [comment]
I would be open to something like that in principle. Would you propose releasing after every merged PR, or bundling several merged changes together? How would you teach new contributors to interact with this system?

**Comment by louib** [comment]
> Would you propose releasing after every merged PR, or bundling several merged changes together?

I think releasing on every master merge would be ideal, in order to reduce the size and risk of the releases. I understand however that you might not be comfortable with that pace of releasing just yet, so I propose two alternatives:
* We could release `-beta` versions on every master merge, and continue to do the stable releases manually.
* We could also create a GitHub Actions workflow that would be triggered manually. This would reduce the toil when creating a release, and thus would probably make us release more often anyway.

We could wait until we are more confident in the unit tests to re-evaluate if we want to release on every master merge.

> How would you teach new contributors to interact with this system?

I would add a CI job that would validate the commit title, and I would add a `CONTRIBUTING.md` file with documentation on our development workflow. First-time contributors will be prompted to read the file before opening their first PR (This is already supported by GitHub).

**Comment by sseemayer** [comment]
Releasing automatically after every merge is fine by me. I will admit to having to adjust my mental model somewhat, but I see the many benefits that such a model has (e.g. making sure that contributions land as quickly as possible). Let's go for your proposed ideal solution.

**Comment by sseemayer** [comment]
One more question, since we are in the `0.x` stage of semantic versioning at the moment: How is a transition to `1.x` handled? 

I would want the compatibility-breaking releases that are automatically created to remain below `1.0.0`, and make it a deliberate step to release a `1.0.0` release when we consider the API of the crate to be somewhat stable.

**Comment by louib** [comment]
I think the semantic release tool will only bump the minor version when there's a breaking change, so we can decide when to bump to version `1.0.0`.

**Comment by sseemayer** [comment]
Alright, then let's go for it!

**Comment by louib** [comment]
Looks like semantic-release will bump the major version of the library on a breaking change, whether or not the major version is currently `0`. There's an issue about that [here](https://github.com/semantic-release/semantic-release/issues/1507) and it looks like we're definitely not the only library maintainers expecting that feature. I propose we wait until version `1.x` is out to automate the releases with semantic-release.

**Comment by louib** [comment]
I think I will use [this action](https://github.com/paulhatch/semantic-version) to compute the next version number. The `enable_prerelease_mode` option will allow us to remain in beta mode (version `0.x`) until we are ready to ship version `1.0`.
