### ISSUE TITLE
Decrypt a KeePass database that uses a keyfile? 

### ISSUE THREAD

**Issue by sts10** [sseemayer/keepass-rs#8]
I was just wondering if there's any way to use this library to decrypt KeePass databases that use both a password and [key file](https://keepass.info/help/base/keys.html), as opposed just a master password. 

I'm guessing that would require changes to this crate, but I thought I'd ask if there's some easy method, like combining the master password and text of the keyfile somehow

**Comment by sseemayer** [comment]
You are correct in that this is not currently supported. I am planning to work a bit on this crate today and might get around to adding this feature, if not I can try to at least dig up some docs on how one would add this!

**Comment by sseemayer** [comment]
I had a nice sunday afternoon hacking session and implemented parsing databases with keyfiles. If you upgrade to `0.3.0`, you can now use this to open up a database from a keyfile:

```rust
let path = Path::new("tests/resources/test_db_with_keyfile.kdbx");
        let kf_path = Path::new("tests/resources/test_key.key");
        let db = Database::open(
            &mut File::open(path)?,
            None,
            Some(&mut File::open(kf_path)?),
)?;
```

**Comment by sts10** [comment]
Thanks again. Looks like it's working well for [the tool I'm playing around with](https://github.com/sts10/medic).

**Comment by sseemayer** [comment]
That looks really cool - these analyses are definitely very useful to have so I'll check it out for my personal passwords!
